### ISSUE TITLE
Bitwarden Autofill directs to org.ungoogled.chromium

### ISSUE THREAD

**Issue by sivuda** [wchen342/ungoogled-chromium-android#38] opened 2020-06-08 20:34 UTC
Please at least answer all questions marked with * below. Issues without answering these questions will be closed.

**\*Device info (please complete the following information):**
 - Device: OnePlus 5T
 - OS: Stock
 - Arch: arm64
 - Variant: chromium extension
 - Version: 83.0.4103.97
 
**\*Is the bug related to extensions?**
No

**\*If not related to extensions, can the bug be reproduced with corresponding Chromium version?**
Yes

**\*Describe the bug**
When trying to log into any website using Bitwarden Autofill, it directs to org.ungoogled.chromium instead of relevant login

**\*To Reproduce**
1. Go to any website and login
2. Bitwarden Autofill notification appears
3. Select the notification
4. It shows org.ungoogled.chromium instead of website

**\*Expected behavior**
Need to direct to the relevant website that user is trying to login

**Screenshots**

**Additional context**
Autofill works fine with other browsers including Bromite

**Comment by wchen342** [comment] 2020-06-08 20:52
I'm confused. Your variant says extension but then you said it's not related to extension. Also did you mean "no" for reproducibility in Chromium?

**Comment by sivuda** [comment] 2020-06-08 21:15
> I'm confused. Your variant says extension but then you said it's not related to extension. Also did you mean "no" for reproducibility in Chromium?

Im using the extension variant, whereas for testing purposes installed the non extension chrome_public_arm. Had the similar issue through that

**Comment by wchen342** [comment] 2020-06-08 21:25
I see. When it asks "can the bug be reproduced with corresponding Chromium version?" it is actually asking whether this problem also exists in vanilla chromium (the one from Google, i.e. upstream). Guess I need to update the questions.

Anyway is the software you mentioned [this one](https://github.com/bitwarden/mobile)? Not the extension version right?

**Comment by sivuda** [comment] 2020-06-08 21:48
> Anyway is the software you mentioned [this one](https://github.com/bitwarden/mobile)? Not the extension version right?

Yes, thats it. Not the browser extension

**Comment by wchen342** [comment] 2020-06-08 21:55
How do you get the autofill service to pop up? Do you need to add the Login first manully? I tried to add a Google login but the autofill does not pop up. I also tried to not add login first but go directly to BitWarden Web Vault (I used its website as a test) and login, but there is no pop up too.

EDIT: I have enabled the autofill service.

EDIT2: Ok I got it. I need to enable accessibility service even on Android 10. No idea why though.

**Comment by wchen342** [comment] 2020-06-09 07:24
I spotted the problem to be https://github.com/wchen342/ungoogled-chromium-android/blob/master/patches/ungoogled-chromium-android/change-package-name-chromium.patch#L15, but I don't really understand why.

It seems `Bromite` doesn't have the problem, how do you change your package name @csagan5? I searched your patch files but I cannot find where you changed it.

**Comment by csagan5** [comment] 2020-06-12 07:13
@wchen342 the package names I use are `org.bromite.chromium` and `org.bromite.bromite`; they are changed automatically when I switch to building Chromium or Bromite, so they are not part of any patch. This is also on purpose because some users would install their version of the package (with a different signature) and complain about the signature errors during installation; in general everyone using a different signature should use a different package name.

But it's not working either on Bromite without the accessibility workaround, see https://github.com/bitwarden/mobile/issues/159 and https://github.com/Kunzisoft/KeePassDX/issues/551#issuecomment-637814250

**Comment by wchen342** [comment] 2020-06-12 19:52
Should be fixed by upstream in next release.

**Closed as completed by wchen342** 2020-06-12 19:52 UTC
Labels: bug
