### ISSUE TITLE
[Feature Request] Import Bookmarks Through HTML Files

### ISSUE THREAD

**Issue by ghost** [wchen342/ungoogled-chromium-android#32] opened 2020-06-02 07:15 UTC
**Is your feature request fall into the scope of ungoogled-chromium?**
Yes

**Please describe the feature you would like to have**
Since bookmarks are something that is important to have, I would love to see the Option to Import Bookmarks through a HTML File, without the need for Google Sync

**Describe the solution you'd like**
Lets say you have some bookmarks you want to have on the go but you are not near your PC, if you have Exported Your bookmarks through the PC and copied them to your Phone, you could go into The browser and select Import Bookmarks, from there, the browser will ask where the file is on your Phone, once you select the HTML File containing the Bookmarks, it will then import it and have your bookmarks displayed in the Bookmarks menu

**Describe alternatives you've considered**
I have not found any other ways of attempting this but this is the only way to do it

**Comment by wchen342** [comment] 2020-06-02 07:21
Duplicate of #26.

**Closed as completed** 2020-06-03 20:39 UTC
