### ISSUE TITLE
Broken FDroid Link On README.md

### ISSUE THREAD

**Issue by ghost** [wchen342/ungoogled-chromium-android#25] opened 2020-05-30 20:27 UTC
Hello there, I was wondering if you are aware of the broken FDroid Repo Link on the Readme.md?

**Comment by wchen342** [comment] 2020-05-30 20:43
It works fine here. What is the problem?

**Comment by ghost** [comment] 2020-05-30 20:47
The issue is that, when I clicked the FDroid Repo Link, it takes me to a page that says 403 Forbidden, i tried to copy this Github Repo link into FDroid but its not signed and I cannot find the Android Builds on the Directory in FDroid

**Comment by wchen342** [comment] 2020-05-30 20:53
> when I clicked the FDroid Repo Link, it takes me to a page that says 403 Forbidden

The link is not meant to be opened in browsers.

> i tried to copy this Github Repo link into FDroid but its not signed

I didn't add fingerprint in the link. I will add it later.

> I cannot find the Android Builds on the Directory in FDroid

Do you see the packages if you go to categories and click search?

**Comment by ghost** [comment] 2020-05-30 20:59
I did not see any packages when i went to Catagories and clicked search

**Comment by wchen342** [comment] 2020-05-30 21:30
Ok I think I can reproduce now. But I cannot seem to find the reason. Can you confirm you can open [https://www.droidware.info/fdroid/repo/ChromePublic_arm64.apk](https://www.droidware.info/fdroid/repo/ChromePublic_arm64.apk) fine in a browser?

**Comment by ghost** [comment] 2020-05-30 21:32
Yes, that link opens in my Browser

**Comment by wchen342** [comment] 2020-05-30 22:22
So the web server is fine. It seems if I have the package installed then I can see it in f-droid client through search. I tried update my f-droid server tools and re-uploaded, but the problem is still there.

The f-droid server tools seems to be not supporting chromium apks very well and I have always had trouble with it recognizing these apks. I think this is more of f-droid's problem, and how to fix their tools is beyond my knowledge. For now can you try the workaround above?

**Comment by ghost** [comment] 2020-05-30 22:24
Yes

**Comment by wchen342** [comment] 2020-05-30 22:25
Actually if you are using the official client, go to settings - select "Expert mode" - tick "Force old index format", kill your client process and re-open. I just tried it an it seems the entries re-appeared that way. Can you give it a try?

**Comment by ghost** [comment] 2020-05-30 22:29
Alright, I tried it and now, what must I search for?

**Comment by wchen342** [comment] 2020-05-30 22:31
On my machine if I enter search then UC will appear by itself. Or you type in "Ungoogled" and it should appear.

**Comment by ghost** [comment] 2020-05-30 22:35
Hmmm nothing popped up or I may have the wrong Repo

**Comment by wchen342** [comment] 2020-05-30 22:41
Did you try the second method I mentioned above?

**Comment by ghost** [comment] 2020-05-30 22:43
Yes but no luck

**Comment by wchen342** [comment] 2020-05-30 22:48
Strange, it worked here..I also cleared the storage for f-droid client though, but if you have other repos set up you may not want to do that.
I am running out of ideas for now. Maybe wait to see whether other people are having the same problem so I can have more information.

**Comment by ghost** [comment] 2020-05-30 22:49
Yes of course

**Comment by wchen342** [comment] 2020-05-30 22:50
I just gave it another try. I think "Force old index format" is unnecessary. Try uncheck that, kill the process and re-open?

**Comment by ghost** [comment] 2020-05-30 22:54
Nothing found

**Comment by wchen342** [comment] 2020-05-30 22:56
Ok I see. I will keep this open and see whether others are facing the same problem.

**Comment by ghost** [comment] 2020-06-01 08:51
F-Droid fetches the `arm` build on an `arm64` device.

![Screenshot_20200601-095024_F-Droid](https://user-images.githubusercontent.com/66112424/83392265-1867eb00-a3f5-11ea-86b5-51c56c67788a.png)

**Comment by stuff97** [comment] 2020-06-01 15:15
hi @MrTeeXD,
- try installing the `Aurora Droid` f-droid client it's FOSS software and it's even avaliable in f-droid: 
[Aurora Droid](https://f-droid.org/en/packages/com.aurora.adroid/)

- create a new repo and add the `ungoogled chromium` link : 
`https://www.droidware.info/fdroid/repo/`

- add the repo name (eg : ungoogled)

- with the repo finger print ( completely optional ) : 
`2144449AB1DD270EC31B6087409B5D0EA39A75A9F290DA62AC1B238A0EAAF851`

- and sync the repo lists, search for `ungoogled` in the main menu, and thats it `ungoogle chromium` shoud appear.

Best regards

**Comment by stuff97** [comment] 2020-06-01 16:51
i can confirm the issue @m54fjt6910tt3o948b1zi840oanas5uty4j3nq2 pointed out on both `f-droid` and `aurora droid`.

**Comment by wchen342** [comment] 2020-06-01 16:57
@xradiation @m54fjt6910tt3o948b1zi840oanas5uty4j3nq2 I changed it for better compatibility. I forgot to mention it in README. Is there a problem with updating?

**Comment by stuff97** [comment] 2020-06-01 17:17
hi @wchen342, 
yeah, the issue is persistent on both clients as mentioned above, and I've just opened a new issue to address this problem.

**Comment by wchen342** [comment] 2020-06-01 18:13
@xradiation I re-uploaded all files. Can you try again?

**Comment by ghost** [comment] 2020-06-01 18:20
So, I managed to successfully install Ungoogled Chromium through the Repo that xradiation linked and without Aurora Droid

**Comment by wchen342** [comment] 2020-06-01 18:25
@MrTeeXD I updated the files yesterday. Glad it works now.

**Comment by ghost** [comment] 2020-06-01 18:26
Awesome, well done :D

**Comment by stuff97** [comment] 2020-06-01 18:27
@wchen342 it worked fine this time, appreciated 👍

**Comment by wchen342** [comment] 2020-06-01 18:47
@m54fjt6910tt3o948b1zi840oanas5uty4j3nq2 If you still have problem please let me know. Closing this for now.

**Closed as completed by wchen342** 2020-06-01 18:47 UTC
Labels: help wanted, need info

**Comment by ghost** [comment] 2020-06-01 18:52
@wchen342 @xradiation Sorry, but for me it's worse now. F-Droid doesn't even start downloading any file from your repo. I cleared the cache and added your repo again. but I don't even get to the point where the verification of the downloaded file fails.

**Comment by wchen342** [comment] 2020-06-01 18:55
@m54fjt6910tt3o948b1zi840oanas5uty4j3nq2 F-Droid client seems to have strange problems sometimes. Can you try clearing the data of f-droid client or another client and see whether that works?

**Comment by ghost** [comment] 2020-06-01 19:02
@wchen342 Clearing the data fixed the problem. Thanks.
