### ISSUE TITLE
New Tab Extensions Are Not Working

### ISSUE THREAD

**Issue by borealis999** [wchen342/ungoogled-chromium-android#40] opened 2020-06-09 00:09 UTC
Please at least answer all questions marked with * below. Issues without answering these questions will be closed.

**\*Device info (please complete the following information):**
 - Device: Xiaomi Mi 9T
 - OS: MIUI Global 11.0.5 (Android 10)
 - Arch: arm64
 - Variant: Chrome Public; Extensions
 - Version: 83.0.4103.97.410309700
 
**\*Is the bug related to extensions/on the extension-support version?**
Yes

**\*If not related to extensions/extension-support version, can the bug be reproduced with corresponding non-extension-support ungoogled-chromium-android version?**
N/A

**\*If not related to extensions/extension-support version, can the bug be reproduced with corresponding vanilla Chromium (the one directly from Google) version?**
N/A

**\*Describe the bug**
Even after successfully installing a new tab extension, opening a new tab only opens the stock Chrome new tab instead of the new tab provided by the extension

**\*To Reproduce**
1. Go to https://github.com/zongou/new-tab-zongou/releases (a new tab extension built with the Kiwi Browser in mind)
2. Download source code, extract in a folder other than the Download folder
3. Using dev tools in chrome://extensions, import the extension from the 'dist' folder
4. Once extension has been loaded, click the new tab button. 

**\*Expected behavior**
The new tab interface provided by the extension should open for the new tab page

**Screenshots**

**Additional context**

**Comment by wchen342** [comment] 2020-06-09 00:17
This looks like an extension designed for desktop?

Note that ungoogled-chromium is not meant to exactly replicate Kiwi's functionalities. I will see whether I can find the cause and then decide whether it should be fixed.

**Comment by borealis999** [comment] 2020-06-09 00:37
So apparently the new tab page is chrome-native://newtab, while the extension only affects chrome://newtab. 

Is changing the new tab page from chrome-native://newtab to chrome://newtab something that can be done?

**Comment by wchen342** [comment] 2020-06-09 00:40
How did you reach that conclusion? I tried both urls and they end up with the same page.

**Comment by borealis999** [comment] 2020-06-09 00:44
That was foolish of me. I should have tried both URLs. Sorry. Yeah, it doesn't work on either URLs. 
![image](https://user-images.githubusercontent.com/66651428/84093717-d835d900-a9af-11ea-9547-d9c71fba7a88.png)
![image](https://user-images.githubusercontent.com/66651428/84093725-dec45080-a9af-11ea-91c9-6adb18217dfb.png)

**Comment by wchen342** [comment] 2020-06-09 00:48
I think it has something to do with extensions API. I will investigate this later.

**Comment by wchen342** [comment] 2020-06-22 06:23
Moved to [https://git.droidware.info/wchen342/ungoogled-chromium-android/issues/40](https://git.droidware.info/wchen342/ungoogled-chromium-android/issues/40)

**Closed as completed by wchen342** 2020-06-22 06:23 UTC
Labels: extensions
